apiVersion: 1

datasources:
  - name: ClickHouse
    uid: dataprofiler-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      username: default
      defaultDatabase: default
    secureJsonData:
      password: password123
    isDefault: true
    editable: true

  - name: PostgreSQL-Metrics
    uid: dataprofiler-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: postgres
    user: postgres
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    secureJsonData:
      password: password123
    editable: true
