apiVersion: 1

datasources:
  - name: ClickHouse
    uid: dataprofiler-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      username: default
      defaultDatabase: default
    secureJsonData:
      password: password123
    isDefault: true
    editable: true
