apiVersion: 1

datasources:
  - name: ClickHouse
    uid: dataprofiler-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      server: ${CLICKHOUSE_HOST}
      port: ${CLICKHOUSE_PORT}
      protocol: http
      username: ${CLICKHOUSE_USER}
      defaultDatabase: default
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    isDefault: true
    editable: true

  - name: PostgreSQL-Metrics
    uid: dataprofiler-postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DATABASE}
    user: ${POSTGRES_USER}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: true
    # Note: POSTGRES_HOST/PORT/DATABASE/USER/PASSWORD env vars in Grafana
    # are set to postgres-metrics service values in docker-compose.yml
