apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: default
      port: 8123
      protocol: http
    secureJsonData:
      username: default
      password: password123
    isDefault: true
    editable: true
